
name: test

on:
  workflow_dispatch:
 
        
jobs:
  echo_runner_job:
    environment: TEST
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: "Echo Runner"
        run: echo "Runner - ${{ vars.TESTSIZE128KB }}"
